name: CI

on:
  release:
    types:
      - published

jobs:
  build-adapt-html:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up packages
        run: |
          pip install -r requirements.txt
          npm i

      - name: Build docs
        run: ./build.sh

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: Indico Team
          user_email: indico-team@cern.ch
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
